### ISSUE TITLE
Missing maven-core dependency

### ISSUE THREAD

**Issue by ebourg** [eclipse-sisu/sisu.mojos#9]
Hi,

sisu-mojos depends on maven-core (or formerly maven-project) but doesn't declare an explicit dependency in the pom. The dependency is brought transitively to the classpath through maven-common-artifact-filters. After upgrading to maven-common-artifact-filters 3.3 this is no longer true, and the build fails.

**Comment by kwin** [comment]
All Maven plugins implicitly have maven-core in the classpath (compare with https://maven.apache.org/guides/mini/guide-maven-classloading.html#Plugin_Classloaders) even without listing it explicitly in the pom.xml. Also it is transitively inherited via https://github.com/eclipse/sisu.mojos/blob/fff6dab844d6e9a05fe52cf22e2e844f40b11af5/pom.xml#L123. What exactly is the issue you are facing here. Are you using it as regular Maven plugin or in some other way?

**Comment by ebourg** [comment]
Upgrading maven-common-artifact-filters breaks the build:

	--- a/pom.xml
	+++ b/pom.xml
	@@ -121,7 +121,7 @@
	     <dependency>
	       <groupId>org.apache.maven.shared</groupId>
	       <artifactId>maven-common-artifact-filters</artifactId>
	-      <version>1.4</version>
	+      <version>3.3.2</version>
	       <exclusions>
	         <exclusion>
	           <groupId>org.codehaus.plexus</groupId>



	[INFO] -------------------------------------------------------------
	[ERROR] COMPILATION ERROR :
	[INFO] -------------------------------------------------------------
	[ERROR] /C:/dev/sisu.mojos/src/main/java/org/eclipse/sisu/mojos/TestIndexMojo.java:[21,32] package org.apache.maven.project does not exist
	[ERROR] /C:/dev/sisu.mojos/src/main/java/org/eclipse/sisu/mojos/TestIndexMojo.java:[39,13] cannot find symbol
	  symbol:   class MavenProject
	  location: class org.eclipse.sisu.mojos.TestIndexMojo
	[ERROR] /C:/dev/sisu.mojos/src/main/java/org/eclipse/sisu/mojos/IndexMojo.java:[31,32] package org.apache.maven.project does not exist
	[ERROR] /C:/dev/sisu.mojos/src/main/java/org/eclipse/sisu/mojos/IndexMojo.java:[145,13] cannot find symbol
	  symbol:   class MavenProject
	  location: class org.eclipse.sisu.mojos.IndexMojo
	[ERROR] /C:/dev/sisu.mojos/src/main/java/org/eclipse/sisu/mojos/IndexMojo.java:[168,35] cannot find symbol
	  symbol:   class MavenProject
	  location: class org.eclipse.sisu.mojos.IndexMojo
	[ERROR] /C:/dev/sisu.mojos/src/main/java/org/eclipse/sisu/mojos/MainIndexMojo.java:[21,32] package org.apache.maven.project does not exist
	[ERROR] /C:/dev/sisu.mojos/src/main/java/org/eclipse/sisu/mojos/MainIndexMojo.java:[39,13] cannot find symbol
	  symbol:   class MavenProject
	  location: class org.eclipse.sisu.mojos.MainIndexMojo
	[INFO] 7 errors
	[INFO] -------------------------------------------------------------

Because maven-common-artifact-filters no longer brings the maven-project dependency to the classpath.

**Comment by cstamas** [comment]
You need to do the change as in PR https://github.com/eclipse/sisu.mojos/pull/7 (note: it contains a bit older filters)
